version: "1.0"
stages:
  - prepare
  - build
  - push
  - deploy
steps:
  main_clone:
    stage: prepare
    type: git-clone
    repo: atk4/image
    revision: "${{CF_BRANCH}}"

  fix_sha:
    stage: prepare
    title: Propagate Dockerfiles
    image: alpine
    commands:
      - apk add make && make

  build:
    type: parallel
    stage: build
    steps:
      b7.3:
        type: build
        stage: build
        image_name: atk4/build
        tag: candidate-7.3
        registry: atk4
        dockerfile: 7.3/Dockerfile

      b7.4:
        type: build
        stage: build
        image_name: atk4/build
        tag: candidate-7.4
        registry: atk4
        dockerfile: 7.4/Dockerfile
