version: "1.0"
stages:
  - prepare
  - build
  - push
  - deploy
steps:
  main_clone:
    stage: prepare
    type: git-clone
    repo: atk4/image
    revision: "${{CF_BRANCH}}"

  fix_sha:
    stage: prepare
    title: Propagate Dockerfiles
    image: alpine
    commands:
      - apk add make && make

  build:
    type: parallel
    stage: build
    steps:
      b7_2:
        type: build
        stage: build
        image_name: atk4/image
        tag: candidate-7.2
        registry: atk4
        dockerfile: 7.2/Dockerfile

      b7_3:
        type: build
        stage: build
        image_name: atk4/image
        tag: candidate-7.3
        registry: atk4
        dockerfile: 7.3/Dockerfile

      b7_4:
        type: build
        stage: build
        image_name: atk4/image
        tag: candidate-7.4
        registry: atk4
        dockerfile: 7.4/Dockerfile

      b8_0:
        type: build
        stage: build
        image_name: atk4/image
        tag: candidate-8.0
        registry: atk4
        dockerfile: 8.0.0beta3/Dockerfile
