version: "1.0"
stages:
  - prepare
  - build_base
  - build_npm
  - build_selenium
  - test
  - push
steps:
  main_clone:
    stage: prepare
    type: git-clone
    repo: atk4/image
    revision: "${{CF_BRANCH}}"

  build_base:
    type: parallel
    stage: build_base
    steps:
      b5_dot_6:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-5.6"
        registry: atk4
        dockerfile: data/5.6/Dockerfile
      b7_dot_0:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-7.0"
        registry: atk4
        dockerfile: data/7.0/Dockerfile
      b7_dot_1:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-7.1"
        registry: atk4
        dockerfile: data/7.1/Dockerfile
      b7_dot_2:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-7.2"
        registry: atk4
        dockerfile: data/7.2/Dockerfile
      b7_dot_3:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-7.3"
        registry: atk4
        dockerfile: data/7.3/Dockerfile
      b7_dot_4:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-7.4"
        registry: atk4
        dockerfile: data/7.4/Dockerfile
      b8_dot_0:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-8.0"
        registry: atk4
        dockerfile: data/8.0/Dockerfile

  build_npm:
    type: parallel
    stage: build_npm
    steps:
      b5_dot_6_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-5.6-npm"
        registry: atk4
        dockerfile: data/5.6/Dockerfile
      b7_dot_0_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-7.0-npm"
        registry: atk4
        dockerfile: data/7.0/Dockerfile
      b7_dot_1_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-7.1-npm"
        registry: atk4
        dockerfile: data/7.1/Dockerfile
      b7_dot_2_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-7.2-npm"
        registry: atk4
        dockerfile: data/7.2/Dockerfile
      b7_dot_3_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-7.3-npm"
        registry: atk4
        dockerfile: data/7.3/Dockerfile
      b7_dot_4_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-7.4-npm"
        registry: atk4
        dockerfile: data/7.4/Dockerfile
      b8_dot_0_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-8.0-npm"
        registry: atk4
        dockerfile: data/8.0/Dockerfile

  build_selenium:
    type: parallel
    stage: build_selenium
    steps:
      b5_dot_6_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-5.6-selenium"
        registry: atk4
        dockerfile: data/5.6/Dockerfile
      b7_dot_0_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-7.0-selenium"
        registry: atk4
        dockerfile: data/7.0/Dockerfile
      b7_dot_1_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-7.1-selenium"
        registry: atk4
        dockerfile: data/7.1/Dockerfile
      b7_dot_2_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-7.2-selenium"
        registry: atk4
        dockerfile: data/7.2/Dockerfile
      b7_dot_3_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-7.3-selenium"
        registry: atk4
        dockerfile: data/7.3/Dockerfile
      b7_dot_4_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-7.4-selenium"
        registry: atk4
        dockerfile: data/7.4/Dockerfile
      b8_dot_0_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-8.0-selenium"
        registry: atk4
        dockerfile: data/8.0/Dockerfile

  test:
    type: parallel
    stage: test
    steps:
      t5_dot_6:
        image: "atk4/image:${{CF_BUILD_ID}}-5.6"
        registry: atk4
        commands:
          - php test.php
      t7_dot_0:
        image: "atk4/image:${{CF_BUILD_ID}}-7.0"
        registry: atk4
        commands:
          - php test.php
      t7_dot_1:
        image: "atk4/image:${{CF_BUILD_ID}}-7.1"
        registry: atk4
        commands:
          - php test.php
      t7_dot_2:
        image: "atk4/image:${{CF_BUILD_ID}}-7.2"
        registry: atk4
        commands:
          - php test.php
      t7_dot_3:
        image: "atk4/image:${{CF_BUILD_ID}}-7.3"
        registry: atk4
        commands:
          - php test.php
      t7_dot_4:
        image: "atk4/image:${{CF_BUILD_ID}}-7.4"
        registry: atk4
        commands:
          - php test.php
      t8_dot_0:
        image: "atk4/image:${{CF_BUILD_ID}}-8.0"
        registry: atk4
        commands:
          - php test.php
      t5_dot_6_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-5.6-npm"
        registry: atk4
        commands:
          - php test.php
      t7_dot_0_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-7.0-npm"
        registry: atk4
        commands:
          - php test.php
      t7_dot_1_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-7.1-npm"
        registry: atk4
        commands:
          - php test.php
      t7_dot_2_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-7.2-npm"
        registry: atk4
        commands:
          - php test.php
      t7_dot_3_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-7.3-npm"
        registry: atk4
        commands:
          - php test.php
      t7_dot_4_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-7.4-npm"
        registry: atk4
        commands:
          - php test.php
      t8_dot_0_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-8.0-npm"
        registry: atk4
        commands:
          - php test.php
      t5_dot_6_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-5.6-selenium"
        registry: atk4
        commands:
          - php test.php
      t7_dot_0_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.0-selenium"
        registry: atk4
        commands:
          - php test.php
      t7_dot_1_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.1-selenium"
        registry: atk4
        commands:
          - php test.php
      t7_dot_2_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.2-selenium"
        registry: atk4
        commands:
          - php test.php
      t7_dot_3_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.3-selenium"
        registry: atk4
        commands:
          - php test.php
      t7_dot_4_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.4-selenium"
        registry: atk4
        commands:
          - php test.php
      t8_dot_0_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-8.0-selenium"
        registry: atk4
        commands:
          - php test.php

  push:
    type: parallel
    stage: push
    when:
      branch:
        only:
          - master
    steps:
      p5_dot_6:
        candidate: "${{b5_dot_6}}"
        type: push
        registry: atk4
        tag: "5.6"
      p5:
        candidate: "${{b5}}"
        type: push
        registry: atk4
        tag: "5"
      p7_dot_0:
        candidate: "${{b7_dot_0}}"
        type: push
        registry: atk4
        tag: "7.0"
      p7_dot_1:
        candidate: "${{b7_dot_1}}"
        type: push
        registry: atk4
        tag: "7.1"
      p7_dot_2:
        candidate: "${{b7_dot_2}}"
        type: push
        registry: atk4
        tag: "7.2"
      p7_dot_3:
        candidate: "${{b7_dot_3}}"
        type: push
        registry: atk4
        tag: "7.3"
      p7_dot_4:
        candidate: "${{b7_dot_4}}"
        type: push
        registry: atk4
        tag: "7.4"
      p7:
        candidate: "${{b7}}"
        type: push
        registry: atk4
        tag: "7"
      p8_dot_0:
        candidate: "${{b8_dot_0}}"
        type: push
        registry: atk4
        tag: "8.0"
      p8:
        candidate: "${{b8}}"
        type: push
        registry: atk4
        tag: "8"
      platest:
        candidate: "${{blatest}}"
        type: push
        registry: atk4
        tag: "latest"
      p5_dot_6_dash_npm:
        candidate: "${{b5_dot_6_dash_npm}}"
        type: push
        registry: atk4
        tag: "5.6-npm"
      p5_dash_npm:
        candidate: "${{b5_dash_npm}}"
        type: push
        registry: atk4
        tag: "5-npm"
      p7_dot_0_dash_npm:
        candidate: "${{b7_dot_0_dash_npm}}"
        type: push
        registry: atk4
        tag: "7.0-npm"
      p7_dot_1_dash_npm:
        candidate: "${{b7_dot_1_dash_npm}}"
        type: push
        registry: atk4
        tag: "7.1-npm"
      p7_dot_2_dash_npm:
        candidate: "${{b7_dot_2_dash_npm}}"
        type: push
        registry: atk4
        tag: "7.2-npm"
      p7_dot_3_dash_npm:
        candidate: "${{b7_dot_3_dash_npm}}"
        type: push
        registry: atk4
        tag: "7.3-npm"
      p7_dot_4_dash_npm:
        candidate: "${{b7_dot_4_dash_npm}}"
        type: push
        registry: atk4
        tag: "7.4-npm"
      p7_dash_npm:
        candidate: "${{b7_dash_npm}}"
        type: push
        registry: atk4
        tag: "7-npm"
      p8_dot_0_dash_npm:
        candidate: "${{b8_dot_0_dash_npm}}"
        type: push
        registry: atk4
        tag: "8.0-npm"
      p8_dash_npm:
        candidate: "${{b8_dash_npm}}"
        type: push
        registry: atk4
        tag: "8-npm"
      platest_dash_npm:
        candidate: "${{blatest_dash_npm}}"
        type: push
        registry: atk4
        tag: "latest-npm"
      p5_dot_6_dash_selenium:
        candidate: "${{b5_dot_6_dash_selenium}}"
        type: push
        registry: atk4
        tag: "5.6-selenium"
      p5_dash_selenium:
        candidate: "${{b5_dash_selenium}}"
        type: push
        registry: atk4
        tag: "5-selenium"
      p7_dot_0_dash_selenium:
        candidate: "${{b7_dot_0_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.0-selenium"
      p7_dot_1_dash_selenium:
        candidate: "${{b7_dot_1_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.1-selenium"
      p7_dot_2_dash_selenium:
        candidate: "${{b7_dot_2_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.2-selenium"
      p7_dot_3_dash_selenium:
        candidate: "${{b7_dot_3_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.3-selenium"
      p7_dot_4_dash_selenium:
        candidate: "${{b7_dot_4_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.4-selenium"
      p7_dash_selenium:
        candidate: "${{b7_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7-selenium"
      p8_dot_0_dash_selenium:
        candidate: "${{b8_dot_0_dash_selenium}}"
        type: push
        registry: atk4
        tag: "8.0-selenium"
      p8_dash_selenium:
        candidate: "${{b8_dash_selenium}}"
        type: push
        registry: atk4
        tag: "8-selenium"
      platest_dash_selenium:
        candidate: "${{blatest_dash_selenium}}"
        type: push
        registry: atk4
        tag: "latest-selenium"
