version: "1.0"
stages:
  - prepare
  - build
  - test
  - push
steps:
  main_clone:
    stage: prepare
    type: git-clone
    repo: atk4/image
    revision: "${{CF_BRANCH}}"

  build:
    type: parallel
    stage: build
    steps:
      b7.2:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-7.2"
        registry: atk4
        dockerfile: 7.2/Dockerfile
      b7.3:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-7.3"
        registry: atk4
        dockerfile: 7.3/Dockerfile
      b7.4:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-7.4"
        registry: atk4
        dockerfile: 7.4/Dockerfile
      b8.0:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-8.0"
        registry: atk4
        dockerfile: 8.0/Dockerfile

  test:
    type: parallel
    stage: test
    steps:
      t7.2:
        image: "atk4/image:${{CF_BUILD_ID}}-7.2"
        registry: atk4
        commands:
          - php test.php
      t7.3:
        image: "atk4/image:${{CF_BUILD_ID}}-7.3"
        registry: atk4
        commands:
          - php test.php
      t7.4:
        image: "atk4/image:${{CF_BUILD_ID}}-7.4"
        registry: atk4
        commands:
          - php test.php
      t8.0:
        image: "atk4/image:${{CF_BUILD_ID}}-8.0"
        registry: atk4
        commands:
          - php test.php

  push:
    type: parallel
    stage: push
    when:
      branch:
        only:
          - master
    steps:
      p7.2:
        candidate: "${{b7.2}}"
        type: push
        registry: atk4
        tag: "7.2"
      p7.3:
        candidate: "${{b7.3}}"
        type: push
        registry: atk4
        tag: "7.3"
      p7.4:
        candidate: "${{b7.4}}"
        type: push
        registry: atk4
        tag: "7.4"
      platest:
        candidate: "${{b7.4}}"
        type: push
        registry: atk4
        tag: "latest"
      p8.0:
        candidate: "${{b8.0}}"
        type: push
        registry: atk4
        tag: "8.0"
