version: "1.0"
stages:
  - prepare
  - build_base
  - build_npm
  - build_selenium
  - test
  - push
steps:
  main_clone:
    stage: prepare
    type: git-clone
    repo: atk4/image
    revision: master

  build_base:
    type: parallel
    stage: build_base
    steps:
      b7_dot_2:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-7.2"
        dockerfile: data/7.2/Dockerfile
      b7_dot_3:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-7.3"
        dockerfile: data/7.3/Dockerfile
      b7_dot_4:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-7.4"
        dockerfile: data/7.4/Dockerfile
      b8_dot_0:
        type: build
        image_name: atk4/image
        target: base
        tag: "${{CF_BUILD_ID}}-8.0"
        dockerfile: data/8.0/Dockerfile

  build_npm:
    type: parallel
    stage: build_npm
    steps:
      b7_dot_2_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-7.2-npm"
        dockerfile: data/7.2/Dockerfile
      b7_dot_3_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-7.3-npm"
        dockerfile: data/7.3/Dockerfile
      b7_dot_4_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-7.4-npm"
        dockerfile: data/7.4/Dockerfile
      b8_dot_0_dash_npm:
        type: build
        image_name: atk4/image
        target: npm
        tag: "${{CF_BUILD_ID}}-8.0-npm"
        dockerfile: data/8.0/Dockerfile

  build_selenium:
    type: parallel
    stage: build_selenium
    steps:
      b7_dot_2_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-7.2-selenium"
        dockerfile: data/7.2/Dockerfile
      b7_dot_3_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-7.3-selenium"
        dockerfile: data/7.3/Dockerfile
      b7_dot_4_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-7.4-selenium"
        dockerfile: data/7.4/Dockerfile
      b8_dot_0_dash_selenium:
        type: build
        image_name: atk4/image
        target: selenium
        tag: "${{CF_BUILD_ID}}-8.0-selenium"
        dockerfile: data/8.0/Dockerfile

  test:
    type: parallel
    stage: test
    steps:
      t7_dot_2:
        image: "atk4/image:${{CF_BUILD_ID}}-7.2"
        commands:
          - php test.php
      t7_dot_3:
        image: "atk4/image:${{CF_BUILD_ID}}-7.3"
        commands:
          - php test.php
      t7_dot_4:
        image: "atk4/image:${{CF_BUILD_ID}}-7.4"
        commands:
          - php test.php
      t8_dot_0:
        image: "atk4/image:${{CF_BUILD_ID}}-8.0"
        commands:
          - php test.php
      t7_dot_2_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-7.2-npm"
        commands:
          - php test.php
      t7_dot_3_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-7.3-npm"
        commands:
          - php test.php
      t7_dot_4_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-7.4-npm"
        commands:
          - php test.php
      t8_dot_0_dash_npm:
        image: "atk4/image:${{CF_BUILD_ID}}-8.0-npm"
        commands:
          - php test.php
      t7_dot_2_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.2-selenium"
        commands:
          - php test.php
      t7_dot_3_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.3-selenium"
        commands:
          - php test.php
      t7_dot_4_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.4-selenium"
        commands:
          - php test.php
      t8_dot_0_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-8.0-selenium"
        commands:
          - php test.php

  push:
    type: parallel
    stage: push
    when:
      branch:
        only:
          - master
    steps:
      p7_dot_2:
        candidate: "${{b7_dot_2}}"
        type: push
        registry: atk4
        tag: "7.2"
      p7_dot_3:
        candidate: "${{b7_dot_3}}"
        type: push
        registry: atk4
        tag: "7.3"
      p7_dot_4:
        candidate: "${{b7_dot_4}}"
        type: push
        registry: atk4
        tag: "7.4"
      p7_dot_x:
        candidate: "${{b7_dot_4}}"
        type: push
        registry: atk4
        tag: "7.x"
      p8_dot_0:
        candidate: "${{b8_dot_0}}"
        type: push
        registry: atk4
        tag: "8.0"
      p8_dot_x:
        candidate: "${{b8_dot_0}}"
        type: push
        registry: atk4
        tag: "8.x"
      platest:
        candidate: "${{b8_dot_0}}"
        type: push
        registry: atk4
        tag: "latest"
      p7_dot_2_dash_npm:
        candidate: "${{b7_dot_2_dash_npm}}"
        type: push
        registry: atk4
        tag: "7.2-npm"
      p7_dot_3_dash_npm:
        candidate: "${{b7_dot_3_dash_npm}}"
        type: push
        registry: atk4
        tag: "7.3-npm"
      p7_dot_4_dash_npm:
        candidate: "${{b7_dot_4_dash_npm}}"
        type: push
        registry: atk4
        tag: "7.4-npm"
      p7_dot_x_dash_npm:
        candidate: "${{b7_dot_4_dash_npm}}"
        type: push
        registry: atk4
        tag: "7.x-npm"
      p8_dot_0_dash_npm:
        candidate: "${{b8_dot_0_dash_npm}}"
        type: push
        registry: atk4
        tag: "8.0-npm"
      p8_dot_x_dash_npm:
        candidate: "${{b8_dot_0_dash_npm}}"
        type: push
        registry: atk4
        tag: "8.x-npm"
      platest_dash_npm:
        candidate: "${{b8_dot_0_dash_npm}}"
        type: push
        registry: atk4
        tag: "latest-npm"
      p7_dot_2_dash_selenium:
        candidate: "${{b7_dot_2_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.2-selenium"
      p7_dot_3_dash_selenium:
        candidate: "${{b7_dot_3_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.3-selenium"
      p7_dot_4_dash_selenium:
        candidate: "${{b7_dot_4_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.4-selenium"
      p7_dot_x_dash_selenium:
        candidate: "${{b7_dot_4_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.x-selenium"
      p8_dot_0_dash_selenium:
        candidate: "${{b8_dot_0_dash_selenium}}"
        type: push
        registry: atk4
        tag: "8.0-selenium"
      p8_dot_x_dash_selenium:
        candidate: "${{b8_dot_0_dash_selenium}}"
        type: push
        registry: atk4
        tag: "8.x-selenium"
      platest_dash_selenium:
        candidate: "${{b8_dot_0_dash_selenium}}"
        type: push
        registry: atk4
        tag: "latest-selenium"
