version: "1.0"
stages:
  - prepare
  - build
  - test
  - push
steps:
  main_clone:
    stage: prepare
    type: git-clone
    repo: atk4/image
    revision: "${{CF_BRANCH}}"

  build:
    type: build
    image_name: atk4/site
    tag: "${{CF_BUILD_ID}}-runtime"
    stage: build
    registry: atk4
    dockerfile: runtime/Dockerfile

  test:
    #image: "atk4/image:${{CF_BUILD_ID}}-runtime"
    image: "${{build}}"
    stage: test
    registry: atk4
    commands:
      - php test.php

  push:
    candidate: "${{build}}"
    type: push
    stage: push
    registry: atk4
    tag: "runtime"
