version: "1.0"
stages:
  - prepare
  - build
  - build-selenium
  - test
  - test-selenium
  - push
steps:
  main_clone:
    stage: prepare
    type: git-clone
    repo: atk4/image
    revision: "${{CF_BRANCH}}"

  build:
    type: parallel
    stage: build
    steps:
      b7_dot_2:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-7.2"
        registry: atk4
        dockerfile: data/7.2/Dockerfile
      b7_dot_3:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-7.3"
        registry: atk4
        dockerfile: data/7.3/Dockerfile
      b7_dot_4:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-7.4"
        registry: atk4
        dockerfile: data/7.4/Dockerfile
      b8_dot_0:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-8.0"
        registry: atk4
        dockerfile: data/8.0/Dockerfile
  build_selenium:
    type: parallel
    stage: build-selenium
    steps:
      b7_dot_2_dash_selenium:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-7.2-selenium"
        registry: atk4
        dockerfile: data/7.2-selenium/Dockerfile
      b7_dot_3_dash_selenium:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-7.3-selenium"
        registry: atk4
        dockerfile: data/7.3-selenium/Dockerfile
      b7_dot_4_dash_selenium:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-7.4-selenium"
        registry: atk4
        dockerfile: data/7.4-selenium/Dockerfile
      b8_dot_0_dash_selenium:
        type: build
        image_name: atk4/image
        tag: "${{CF_BUILD_ID}}-8.0-selenium"
        registry: atk4
        dockerfile: data/8.0-selenium/Dockerfile

  test:
    type: parallel
    stage: test
    steps:
      t7_dot_2:
        image: "atk4/image:${{CF_BUILD_ID}}-7.2"
        registry: atk4
        commands:
          - php test.php
      t7_dot_3:
        image: "atk4/image:${{CF_BUILD_ID}}-7.3"
        registry: atk4
        commands:
          - php test.php
      t7_dot_4:
        image: "atk4/image:${{CF_BUILD_ID}}-7.4"
        registry: atk4
        commands:
          - php test.php
      t8_dot_0:
        image: "atk4/image:${{CF_BUILD_ID}}-8.0"
        registry: atk4
        commands:
          - php test.php
  test_selenium:
    type: parallel
    stage: test-selenium
    steps:
      t7_dot_2_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.2-selenium"
        registry: atk4
        commands:
          - php test.php
      t7_dot_3_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.3-selenium"
        registry: atk4
        commands:
          - php test.php
      t7_dot_4_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-7.4-selenium"
        registry: atk4
        commands:
          - php test.php
      t8_dot_0_dash_selenium:
        image: "atk4/image:${{CF_BUILD_ID}}-8.0-selenium"
        registry: atk4
        commands:
          - php test.php

  push:
    type: parallel
    stage: push
    when:
      branch:
        only:
          - master
    steps:
      p7_dot_2:
        candidate: "${{b7_dot_2}}"
        type: push
        registry: atk4
        tag: "7.2"
      p7_dot_3:
        candidate: "${{b7_dot_3}}"
        type: push
        registry: atk4
        tag: "7.3"
      p7_dot_4:
        candidate: "${{b7_dot_4}}"
        type: push
        registry: atk4
        tag: "7.4"
      platest:
        candidate: "${{b7_dot_4}}"
        type: push
        registry: atk4
        tag: "latest"
      p8_dot_0:
        candidate: "${{b8_dot_0}}"
        type: push
        registry: atk4
        tag: "8.0"
      p7_dot_2_dash_selenium:
        candidate: "${{b7_dot_2_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.2-selenium"
      p7_dot_3_dash_selenium:
        candidate: "${{b7_dot_3_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.3-selenium"
      p7_dot_4_dash_selenium:
        candidate: "${{b7_dot_4_dash_selenium}}"
        type: push
        registry: atk4
        tag: "7.4-selenium"
      platest_dash_selenium:
        candidate: "${{b7_dot_4_dash_selenium}}"
        type: push
        registry: atk4
        tag: "latest-selenium"
      p8_dot_0_dash_selenium:
        candidate: "${{b8_dot_0_dash_selenium}}"
        type: push
        registry: atk4
        tag: "8.0-selenium"
