name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '20 2 * * *'

jobs:
  unit:
    name: Templating
    if: github.event_name != 'push' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mvorisek/image-php
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Check if files are in-sync"
        run: |
          rm -rf data/
          php make.php
          git diff --exit-code

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ghcr.io
      REGISTRY_IMAGE_NAME: ghcr.io/${{ github.repository }}
    strategy:
      fail-fast: false
      matrix:
        imageName:
          - "7.2-alpine"
          - "7.3-alpine"
          - "7.4-alpine"
          - "8.0-alpine"
          - "7.2-debian"
          - "7.3-debian"
          - "7.4-debian"
          - "8.0-debian"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Target "base - Build Dockerfile'
        # try to build twice to suppress random network issues with Github Actions
        run: >-
          sed -i 's~^[ \t]*~~' data/${{ matrix.imageName }}/Dockerfile
          && (docker build -f data/${{ matrix.imageName }}/Dockerfile --target "base" -t ci-target:base ./
          || docker build -f data/${{ matrix.imageName }}/Dockerfile --target "base" -t ci-target:base ./)

      - name: 'Target "base" - Display layer sizes'
        run: >-
          docker history --no-trunc --format "table {{.CreatedSince}}\t{{.Size}}\t{{.CreatedBy}}" $(docker images --no-trunc --format='{{.ID}}' | head -1)
          && docker images --no-trunc --format "Total size: {{.Size}}\t{{.ID}}" | grep $(docker images --no-trunc --format='{{.ID}}' | head -1) | cut -f1

      - name: 'Target "npm - Build Dockerfile'
        # try to build twice to suppress random network issues with Github Actions
        run: >-
          sed -i 's~^[ \t]*~~' data/${{ matrix.imageName }}/Dockerfile
          && (docker build -f data/${{ matrix.imageName }}/Dockerfile --target "npm" -t ci-target:npm ./
          || docker build -f data/${{ matrix.imageName }}/Dockerfile --target "npm" -t ci-target:npm ./)

      - name: 'Target "npm" - Display layer sizes'
        run: >-
          docker history --no-trunc --format "table {{.CreatedSince}}\t{{.Size}}\t{{.CreatedBy}}" $(docker images --no-trunc --format='{{.ID}}' | head -1)
          && docker images --no-trunc --format "Total size: {{.Size}}\t{{.ID}}" | grep $(docker images --no-trunc --format='{{.ID}}' | head -1) | cut -f1

      - name: 'Target "selenium - Build Dockerfile'
        # try to build twice to suppress random network issues with Github Actions
        run: >-
          sed -i 's~^[ \t]*~~' data/${{ matrix.imageName }}/Dockerfile
          && (docker build -f data/${{ matrix.imageName }}/Dockerfile --target "selenium" -t ci-target:selenium ./
          || docker build -f data/${{ matrix.imageName }}/Dockerfile --target "selenium" -t ci-target:selenium ./)

      - name: 'Target "selenium" - Display layer sizes'
        run: >-
          docker history --no-trunc --format "table {{.CreatedSince}}\t{{.Size}}\t{{.CreatedBy}}" $(docker images --no-trunc --format='{{.ID}}' | head -1)
          && docker images --no-trunc --format "Total size: {{.Size}}\t{{.ID}}" | grep $(docker images --no-trunc --format='{{.ID}}' | head -1) | cut -f1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push tags to registry'
        if: github.ref == 'refs/heads/master'
        run: >-
          if [ "${{ matrix.imageName }}" == "7.2-alpine" ]; then
          docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.2" && docker push "$REGISTRY_IMAGE_NAME:7.2"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.2-alpine" && docker push "$REGISTRY_IMAGE_NAME:7.2-alpine"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.2-npm" && docker push "$REGISTRY_IMAGE_NAME:7.2-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.2-alpine-npm" && docker push "$REGISTRY_IMAGE_NAME:7.2-alpine-npm"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.2-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.2-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.2-alpine-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.2-alpine-selenium"
          ; fi
          && if [ "${{ matrix.imageName }}" == "7.3-alpine" ]; then
          docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.3" && docker push "$REGISTRY_IMAGE_NAME:7.3"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.3-alpine" && docker push "$REGISTRY_IMAGE_NAME:7.3-alpine"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.3-npm" && docker push "$REGISTRY_IMAGE_NAME:7.3-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.3-alpine-npm" && docker push "$REGISTRY_IMAGE_NAME:7.3-alpine-npm"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.3-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.3-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.3-alpine-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.3-alpine-selenium"
          ; fi
          && if [ "${{ matrix.imageName }}" == "7.4-alpine" ]; then
          docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.4" && docker push "$REGISTRY_IMAGE_NAME:7.4"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.4-alpine" && docker push "$REGISTRY_IMAGE_NAME:7.4-alpine"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.x" && docker push "$REGISTRY_IMAGE_NAME:7.x"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.x-alpine" && docker push "$REGISTRY_IMAGE_NAME:7.x-alpine"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.4-npm" && docker push "$REGISTRY_IMAGE_NAME:7.4-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.4-alpine-npm" && docker push "$REGISTRY_IMAGE_NAME:7.4-alpine-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.x-npm" && docker push "$REGISTRY_IMAGE_NAME:7.x-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.x-alpine-npm" && docker push "$REGISTRY_IMAGE_NAME:7.x-alpine-npm"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.4-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.4-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.4-alpine-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.4-alpine-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.x-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.x-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.x-alpine-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.x-alpine-selenium"
          ; fi
          && if [ "${{ matrix.imageName }}" == "8.0-alpine" ]; then
          docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:8.0" && docker push "$REGISTRY_IMAGE_NAME:8.0"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:8.0-alpine" && docker push "$REGISTRY_IMAGE_NAME:8.0-alpine"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:8.x" && docker push "$REGISTRY_IMAGE_NAME:8.x"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:8.x-alpine" && docker push "$REGISTRY_IMAGE_NAME:8.x-alpine"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:latest" && docker push "$REGISTRY_IMAGE_NAME:latest"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:latest-alpine" && docker push "$REGISTRY_IMAGE_NAME:latest-alpine"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:8.0-npm" && docker push "$REGISTRY_IMAGE_NAME:8.0-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:8.0-alpine-npm" && docker push "$REGISTRY_IMAGE_NAME:8.0-alpine-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:8.x-npm" && docker push "$REGISTRY_IMAGE_NAME:8.x-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:8.x-alpine-npm" && docker push "$REGISTRY_IMAGE_NAME:8.x-alpine-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:latest-npm" && docker push "$REGISTRY_IMAGE_NAME:latest-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:latest-alpine-npm" && docker push "$REGISTRY_IMAGE_NAME:latest-alpine-npm"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:8.0-selenium" && docker push "$REGISTRY_IMAGE_NAME:8.0-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:8.0-alpine-selenium" && docker push "$REGISTRY_IMAGE_NAME:8.0-alpine-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:8.x-selenium" && docker push "$REGISTRY_IMAGE_NAME:8.x-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:8.x-alpine-selenium" && docker push "$REGISTRY_IMAGE_NAME:8.x-alpine-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:latest-selenium" && docker push "$REGISTRY_IMAGE_NAME:latest-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:latest-alpine-selenium" && docker push "$REGISTRY_IMAGE_NAME:latest-alpine-selenium"
          ; fi
          && if [ "${{ matrix.imageName }}" == "7.2-debian" ]; then
          docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.2-debian" && docker push "$REGISTRY_IMAGE_NAME:7.2-debian"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.2-debian-npm" && docker push "$REGISTRY_IMAGE_NAME:7.2-debian-npm"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.2-debian-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.2-debian-selenium"
          ; fi
          && if [ "${{ matrix.imageName }}" == "7.3-debian" ]; then
          docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.3-debian" && docker push "$REGISTRY_IMAGE_NAME:7.3-debian"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.3-debian-npm" && docker push "$REGISTRY_IMAGE_NAME:7.3-debian-npm"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.3-debian-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.3-debian-selenium"
          ; fi
          && if [ "${{ matrix.imageName }}" == "7.4-debian" ]; then
          docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.4-debian" && docker push "$REGISTRY_IMAGE_NAME:7.4-debian"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:7.x-debian" && docker push "$REGISTRY_IMAGE_NAME:7.x-debian"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.4-debian-npm" && docker push "$REGISTRY_IMAGE_NAME:7.4-debian-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:7.x-debian-npm" && docker push "$REGISTRY_IMAGE_NAME:7.x-debian-npm"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.4-debian-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.4-debian-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:7.x-debian-selenium" && docker push "$REGISTRY_IMAGE_NAME:7.x-debian-selenium"
          ; fi
          && if [ "${{ matrix.imageName }}" == "8.0-debian" ]; then
          docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:8.0-debian" && docker push "$REGISTRY_IMAGE_NAME:8.0-debian"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:8.x-debian" && docker push "$REGISTRY_IMAGE_NAME:8.x-debian"
          && docker tag "ci-target:base" "$REGISTRY_IMAGE_NAME:latest-debian" && docker push "$REGISTRY_IMAGE_NAME:latest-debian"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:8.0-debian-npm" && docker push "$REGISTRY_IMAGE_NAME:8.0-debian-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:8.x-debian-npm" && docker push "$REGISTRY_IMAGE_NAME:8.x-debian-npm"
          && docker tag "ci-target:npm" "$REGISTRY_IMAGE_NAME:latest-debian-npm" && docker push "$REGISTRY_IMAGE_NAME:latest-debian-npm"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:8.0-debian-selenium" && docker push "$REGISTRY_IMAGE_NAME:8.0-debian-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:8.x-debian-selenium" && docker push "$REGISTRY_IMAGE_NAME:8.x-debian-selenium"
          && docker tag "ci-target:selenium" "$REGISTRY_IMAGE_NAME:latest-debian-selenium" && docker push "$REGISTRY_IMAGE_NAME:latest-debian-selenium"
          ; fi
