name: Build

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  unit:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        imageName:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Dockerfile
        run: docker build -f data/${{ matrix.imageName }}/Dockerfile ./
